import type { NextPage } from 'next'
import Head from 'next/head'
import { useMemo } from 'react'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const currentYear = useMemo(() => new Date().getFullYear().toString(), [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Undisclosed | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Undisclosed
        </h1>

        <p className={styles.description}>
          This page is currently under construction.
        </p>
      </main>

      <footer className={styles.footer}>
        Copyright &copy; <span>{currentYear}</span>&nbsp;Undisclosed
      </footer>
    </div>
  )
}

export default Home
