import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

import { Footer } from './../components'
import { footerHeight } from './../themes'

import styles from '../styles/Home.module.css'

const Main = styled.main`
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  min-height: calc(100vh - ${footerHeight}px);
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Undisclosed | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1 className={styles.title}>
          Undisclosed
        </h1>

        <p className={styles.description}>
          This page is currently under construction.
        </p>
      </Main>

      <Footer />
    </>
  )
}

export default Home
